FROM golang:1.13-alpine As builder

RUN mkdir -p $GOPATH/src/apirest && apk add gcc g++ git

WORKDIR $GOPATH/src/apirest

ENV GO111MODULE=on

COPY . .

WORKDIR $GOPATH/src/apirest

RUN go build ./... && go build

FROM alpine

RUN apk --no-cache add ca-certificates bash

WORKDIR /root/

COPY --from=builder /go/src/apirest .

RUN chmod +x ./apirest

ENTRYPOINT [ "./api-go-user-post-api" ]

